name: C++ Docker build
on:
  workflow_dispatch:
    inputs:
      my_value:
        description: Provide input parameter
        required: false
        default: '1234'
  push:
    branches: ["**"]
jobs:
  build:
    name: Build with Cmake
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
      - name: Create Docker container
        run: docker build --tag cpp_builder .
      - name: Build
        run: |
          mkdir -p build
          docker run --rm -v $(pwd):/app -w /app/build cpp_builder cmake ..
          docker run --rm -v $(pwd):/app -w /app/build cpp_builder cmake --build .
      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: HelloWorld
          path: ./build/helloWorld
          retention-days: 1
  run_app:
    name: Run app
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download the binary
      uses: actions/download-artifact@v3
      with: 
        name: HelloWorld
    - name: Run the app
      run: |
        chmod +x ./helloWorld
        ./helloWorld ${{ github.event.inputs.my_value }}
        