name: C++ Docker build
on:
  workflow_dispatch:
  push:
    branches: ["**"]
jobs:
  build:
    name: Build with Cmake
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
      - name: Create Docker container
        run: docker build --tag cpp_builder .
      - name: Build
        run: |
          mkdir -p build
          docker run --rm -v $(pwd):/app -w /app/build cpp_builder cmake ..
          docker run --rm -v $(pwd):/app -w /app/build cpp_builder cmake --build .
        
